# This is an example .goreleaser.yaml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: rekap
    main: ./cmd/rekap
    binary: rekap
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

universal_binaries:
  - id: rekap-universal
    ids:
      - rekap
    name_template: "rekap-universal"
    replace: false

archives:
  - id: rekap-archive
    format_overrides:
      - goos: darwin
        format: tar.gz
    name_template: >-
      {{ .ProjectName }}-
      {{- .Version }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}amd64
      {{- else if eq .Arch "386" }}386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE*
      - rekap.1
  
  - id: rekap-binaries
    format_overrides:
      - goos: darwin
        format: binary
    name_template: >-
      {{ .ProjectName }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}amd64
      {{- else if eq .Arch "386" }}386
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - Merge pull request
      - Merge branch

brews:
  - name: rekap
    ids:
      - rekap-archive
    repository:
      owner: alexinslc
      name: homebrew-rekap
    homepage: https://github.com/alexinslc/rekap
    description: "Daily Mac activity summary in your terminal"
    license: MIT
    directory: Formula
    install: |
      bin.install "rekap"
      man1.install "rekap.1"
    test: |
      system "#{bin}/rekap --version"
